name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
        run: docker buildx build --tag valyd8chain/hmy-cli:latest --tag valyd8chain/hmy-cli:${{ github.ref_name }} --platform linux/amd64,linux/arm/v7,linux/arm64 . 
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: docker buildx build --push --tag valyd8chain/hmy-cli:latest --tag valyd8chain/hmy-cli:${{ github.ref_name }} --platform linux/amd64,linux/arm/v7,linux/arm64 .
